const TABDEFS=[["Dashboard","Dashboard"],["Accounting & Finance","Accounting & Finance"],["Admin / Office","Admin / Office"],["Healthcare Admin","Healthcare Admin"],["Professional Services","Professional Services"],["Applied","Applied"],["Disregarded","Disregarded"],["Closed","Closed"],["All Jobs","All Jobs"]];
let jobs=Array.isArray(window.JUNIOR_JOBS)?window.JUNIOR_JOBS:[],currentTab="Dashboard",filters=new Set(),sortKey="rank",sortDir="asc";
const STATUS_KEY="cj_junior_job_tracker_status_v1";
let statusOverrides={};try{statusOverrides=JSON.parse(localStorage.getItem(STATUS_KEY)||"{}")||{};}catch(e){}
const chanceOrder={"Very High":5,"High":4,"Med–High":3.5,"Medium":3,"Med–Low":2.5,"Medium–Low":2.5,"Low":1};
const relOrder={"Excellent":5,"Very High":4.5,"High":4,"Medium":3,"Low–Medium":2,"Low":1};
const statusOrder={"🟢 Apply":1,"🟡 Consider":2,"🟣 Interview":3,"🟠 Waiting":4,"🔵 Applied":5,"✅ Offer":6,"🚫 Disregarded":7,"❌ Closed":8};
const typeOrder={"Vacancy":1,"Internship":2,"Graduate Program":3,"Talent Pool":4,"Register":5};
const firstDirection={rank:"asc",new:"desc",rate:"desc",distance:"asc",employment:"asc",arrangement:"asc",chance:"desc",relevance:"desc",added:"desc",listed:"desc",closing:"asc",type:"asc",status:"asc"};
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
function perthTodayKey(){const p=new Intl.DateTimeFormat("en-AU",{timeZone:"Australia/Perth",day:"2-digit",month:"short",year:"numeric"}).formatToParts(new Date());const x=Object.fromEntries(p.map(v=>[v.type,v.value]));return `${x.year}-${x.month.toLowerCase()}-${String(Number(x.day)).padStart(2,"0")}`;}
function canonicalDate(s){const m=String(s||"").match(/(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{4})/i);return m?`${m[3]}-${m[2].slice(0,3).toLowerCase()}-${String(Number(m[1])).padStart(2,"0")}`:"";}
function parseDate(s){const m=String(s||"").match(/(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{4})/i);return m?new Date(`${m[2]} ${m[1]}, ${m[3]} 23:59:59`):null;}
function isNewToday(j){return canonicalDate(j.date_added)===perthTodayKey();}
function closingSoon(j){const d=parseDate(j.closing);if(!d)return false;const diff=(d-new Date())/86400000;return diff>=0&&diff<=4;}
function appliedJobs(){return applyOverrides(jobs).filter(j=>/Applied|Interview|Waiting|Offer/.test(j.status));}
function applyOverrides(list){return list.map(j=>({...j,status:statusOverrides[j.id]||j.status}));}
function saveOverrides(){try{localStorage.setItem(STATUS_KEY,JSON.stringify(statusOverrides));}catch(e){}}
function setStatus(id,status){statusOverrides[id]=status;saveOverrides();render();}
function clearLocalStatuses(){statusOverrides={};try{localStorage.removeItem(STATUS_KEY);}catch(e){}render();}
function toggleFilter(el){const f=el.dataset.filter;filters.has(f)?filters.delete(f):filters.add(f);el.classList.toggle("on");render();}
function setTab(t){currentTab=t;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));render();}
function baseRows(){let r=applyOverrides(jobs);if(currentTab==="Applied")r=r.filter(j=>/Applied|Interview|Waiting|Offer/.test(j.status));else if(currentTab==="Disregarded")r=r.filter(j=>j.status.includes("Disregarded"));else if(currentTab==="Closed")r=r.filter(j=>j.status.includes("Closed"));else if(currentTab!=="Dashboard"&&currentTab!=="All Jobs")r=r.filter(j=>(j.category||[]).includes(currentTab)&&!/Closed|Disregarded/.test(j.status));else if(currentTab==="Dashboard")r=r.filter(j=>["🟢 Apply","🟡 Consider"].includes(j.status));return r;}
function filteredRows(){let r=baseRows();const q=(document.getElementById("search")?.value||"").trim().toLowerCase();if(q)r=r.filter(j=>[j.role,j.employer,j.location,j.pay,j.career,j.employment,j.arrangement,j.status].join(" ").toLowerCase().includes(q));if(filters.has("new"))r=r.filter(isNewToday);if(filters.has("30"))r=r.filter(j=>(j.pay_max||0)>=30);if(filters.has("pt"))r=r.filter(j=>/part[- ]time/i.test(j.employment));if(filters.has("temp"))r=r.filter(j=>/casual|contract|temp|temporary/i.test(j.employment));if(filters.has("remote"))r=r.filter(j=>/remote|hybrid|wfh/i.test(j.arrangement));if(filters.has("acct"))r=r.filter(j=>(j.category||[]).includes("Accounting & Finance"));if(filters.has("admin"))r=r.filter(j=>(j.category||[]).includes("Admin / Office"));if(filters.has("health"))r=r.filter(j=>(j.category||[]).includes("Healthcare Admin"));if(filters.has("soon"))r=r.filter(closingSoon);return sortRows(r);}
function sortValue(j,key){if(key==="rank")return +j.rank||9999;if(key==="new")return isNewToday(j)?1:0;if(key==="rate")return j.pay_max==null?-1:+j.pay_max;if(key==="distance")return j.distance_km==null?9999:+j.distance_km;if(key==="employment")return(j.employment||"").toLowerCase();if(key==="arrangement")return(j.arrangement||"").toLowerCase();if(key==="chance")return chanceOrder[j.chance]||0;if(key==="relevance")return relOrder[j.relevance_label]||0;if(key==="added"){const d=parseDate(j.date_added);return d?d.getTime():0;}if(key==="listed"){const d=parseDate(j.listed);return d?d.getTime():0;}if(key==="closing"){const d=parseDate(j.closing);return d?d.getTime():Number.MAX_SAFE_INTEGER;}if(key==="type")return typeOrder[j.type]||99;if(key==="status")return statusOrder[j.status]||99;return"";}
function sortRows(r){const dir=sortDir==="asc"?1:-1;return r.slice().sort((a,b)=>{const av=sortValue(a,sortKey),bv=sortValue(b,sortKey);if(typeof av==="string"||typeof bv==="string")return String(av).localeCompare(String(bv))*dir;if(av===bv)return(+a.rank||0)-(+b.rank||0);return(av-bv)*dir;});}
function chooseSort(key){if(sortKey===key)sortDir=sortDir==="asc"?"desc":"asc";else{sortKey=key;sortDir=firstDirection[key]||"asc";}render();}
function arrow(key){return sortKey!==key?'<span class="arrow">↕</span>':`<span class="arrow">${sortDir==="asc"?"▲":"▼"}</span>`;}
function sh(label,key){return `<th class="sortable" onclick="chooseSort('${key}')">${label}${arrow(key)}</th>`;}
function actions(j){const b=[];if(!j.status.includes("Applied"))b.push(`<button class="rowbtn" onclick="setStatus('${j.id}','🔵 Applied')">✓ Applied</button>`);if(!j.status.includes("Disregarded"))b.push(`<button class="rowbtn" onclick="setStatus('${j.id}','🚫 Disregarded')">✕ Disregard</button>`);if(/Disregarded|Closed|Applied/.test(j.status))b.push(`<button class="rowbtn" onclick="setStatus('${j.id}','🟢 Apply')">↩ Restore</button>`);if(!j.status.includes("Consider"))b.push(`<button class="rowbtn" onclick="setStatus('${j.id}','🟡 Consider')">★ Consider</button>`);return b.join("");}
function refreshTabLabels(){const n=applyOverrides(jobs).filter(isNewToday).length;document.querySelectorAll(".tab").forEach(b=>{const base=b.dataset.label||b.textContent;b.dataset.label=base.replace(/\s*\(\d+ new\)$/i,"");b.textContent=b.dataset.tab==="Dashboard"&&n?`${b.dataset.label} (${n} new)`:b.dataset.label;});}
function render(){refreshTabLabels();const r=filteredRows(),all=applyOverrides(jobs),newToday=all.filter(isNewToday).length;document.getElementById("summary").innerHTML=`<div class="kpi newcount"><b>🆕 ${newToday}</b> new today</div><div class="kpi"><b>${r.length}</b> shown</div><div class="kpi"><b>${r.filter(j=>(j.pay_max||0)>=30).length}</b> $30+/hr</div><div class="kpi"><b>${r.filter(j=>/part[- ]time/i.test(j.employment)).length}</b> part-time</div><div class="kpi"><b>${r.filter(j=>(j.distance_km??999)<=15).length}</b> within ~15 km / remote</div>`;const table=document.getElementById("tbl");if(!r.length){table.innerHTML='<tr><td class="empty">No junior jobs match this sheet/filter combination.</td></tr>';return;}table.innerHTML=`<thead><tr>${sh("Rank","rank")}${sh("New?","new")}<th>Role</th><th>Employer</th>${sh("Location / distance","distance")}${sh("Pay — hourly + annual","rate")}${sh("Employment","employment")}${sh("Work arrangement","arrangement")}${sh("Chance","chance")}${sh("Relevance","relevance")}${sh("Date added","added")}${sh("Listed","listed")}${sh("Closing","closing")}${sh("Type","type")}${sh("Status","status")}<th>Actions</th><th>Source</th></tr></thead><tbody>`+r.map(j=>`<tr><td>${esc(j.rank)}</td><td>${isNewToday(j)?'<span class="newpill">🆕 NEW</span>':'—'}</td><td class="role">${esc(j.role)}</td><td class="employer">${esc(j.employer)}</td><td><div>${esc(j.location)}</div><div class="distance">${j.distance_km===0?'Remote / no commute':`≈ ${esc(j.distance_km)} km from Beckenham`}</div></td><td><b>${esc(j.pay)}</b></td><td>${esc(j.employment)}</td><td>${esc(j.arrangement)}</td><td>${esc(j.chance)}</td><td><b>${esc(j.relevance_label)}</b><div>${esc(j.career)}</div></td><td>${esc(j.date_added||'—')}</td><td>${esc(j.listed||'—')}</td><td>${esc(j.closing||'—')}</td><td><span class="badge">${esc(j.type)}</span></td><td class="status">${esc(j.status)}</td><td><div class="rowactions">${actions(j)}</div></td><td>${j.source?`<a class="link" target="_blank" rel="noopener" href="${esc(j.source)}">Open ↗</a>`:'—'}</td></tr>`).join('')+'</tbody>';}
function exportRows(rows){return rows.map(j=>({Rank:j.rank,"New?":isNewToday(j)?"🆕 NEW":"",Role:j.role,Employer:j.employer,Location:j.location,"Distance from Beckenham (km)":j.distance_km,"Pay (hourly + annual)":j.pay,Employment:j.employment,"Work arrangement":j.arrangement,Chance:j.chance,Relevance:j.relevance_label,"Career notes":j.career,"Date added":j.date_added,Listed:j.listed,Closing:j.closing,Type:j.type,Status:j.status,Source:j.source}));}
function loadXLSX(){return new Promise((resolve,reject)=>{if(window.XLSX)return resolve(window.XLSX);const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js";s.onload=()=>resolve(window.XLSX);s.onerror=()=>reject(new Error("Excel library could not load"));document.head.appendChild(s);});}
async function downloadExcel(){try{const XLSX=await loadXLSX(),wb=XLSX.utils.book_new();const prev=currentTab;["Dashboard","Accounting & Finance","Admin / Office","Healthcare Admin","Professional Services","Applied","Disregarded","Closed","All Jobs"].forEach(name=>{currentTab=name;let rows=baseRows();if(name==="Dashboard")rows=sortRows(rows).slice(0,15);XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(exportRows(rows)),name.slice(0,31));});currentTab=prev;XLSX.writeFile(wb,"CJ_Junior_Jobs_Tracker.xlsx");}catch(e){alert(`Excel download failed: ${e.message}`);}}
function init(){document.getElementById("tabs").innerHTML=TABDEFS.map(([label,key])=>`<button class="tab ${key==="Dashboard"?"active":""}" data-tab="${esc(key)}" data-label="${esc(label)}" onclick="setTab('${esc(key)}')">${esc(label)}</button>`).join("");const meta=window.JUNIOR_TRACKER_META||{};const n=jobs.filter(isNewToday).length;document.getElementById("updated").textContent=`${n?`🆕 ${n} new today • `:""}Junior tracker updated ${meta.updatedAt?new Date(meta.updatedAt).toLocaleString("en-AU",{timeZone:"Australia/Perth"}):""}`;render();}
try{init();}catch(e){document.getElementById("updated").textContent="Junior tracker error";document.getElementById("tbl").innerHTML=`<tr><td class="error">${esc(e.message)}</td></tr>`;}